### ISSUE TITLE
PO excluded from retro?

### ISSUE THREAD

**Issue by trudelle** [basvodde/scrumprimer#27]
The graphic overviews appear show the PO participating in all events except the retrospective. One version even seems to omit the SM too! Primer text initially says the PO is optional, but later says the retro is for the "complete Team". Scrum Guide says it is for the Scrum Team, which includes PO & SM. In your model, does Team != Scrum Team?

Your response to a previous issue acknowledges several other intentional changes. Does your primer correspond to any version of the Guide? If not, why not call attention to these differences as intentional improvements?

**Comment by basvodde** [comment]
In the Scrum Primer, I believe Team is used for Development Team, which is mentioned in the beginning.

Not depicting the SM is mostly to make clear his role is different than the others. The discussion on whether the PO ought to be there is interesting. Scrum Guide tactically says "it is for the Scrum Team" but doesn't go as far as "the entire Scrum Team must be there"

In LeSS, obviously, the PO isn't in the team retrospective.

**Comment by trudelle** [comment]
The Scrum Guide clearly includes the entire Scrum Team (SM, PO and all Development Team members) in the sprint retro, and has for some time. I don't see how Scrum Teams could effectively improve their performance with any members considered optional; the interdependence and shared responsibility for outcomes are for me defining characteristics of a team.  I can understand the development team reflecting on its own, but in my experience it is critical for the PO to regularly participate, at least as important as for other team members. 

I had not realized the extent to which LeSS changes the rules of Scrum. I'm surprised, and disappointed. For me, one of the attractions of LeSS is how it builds on Scrum, but that no longer seems quite true.  I guess it is part of the price of scaling in this manner. At least they participate in the overall retro, which I expect is essential to ensure a focus on improving their ability to generate more value over time.

**Comment by basvodde** [comment]
You can tell me where it "clearly" states that the PO must be in the Retrospective?

Related to LeSS and rules of Scrum. It is the same for Nexus. Because there is only one PO and the team retrospectives are in parallel, therefore the PO won't be able to join all the Retrospective.

**Comment by trudelle** [comment]
They weren't always as clear, but I think it has improved over time. From 2016:
On page 5: "The Scrum Team
The Scrum Team consists of a Product Owner, the Development Team, and a Scrum Master."
On page 12: "Sprint Retrospective
The Sprint Retrospective is an opportunity for the Scrum Team to inspect itself and create a plan for improvements to be enacted during the next Sprint."

Thanks, I now understand the need to for changing the PO role in LeSS/Nexus; and also more fully appreciate your (and/or Craig's) first rule of scaling. I strongly favor using INVEST criteria to enable linearly scaling of feature teams, but for handling significant dependencies across teams, LeSS is the tool I reach for first.

**Comment by basvodde** [comment]
Re Scrum Guide: Yes, but this is a point where the Scrum Guide is purposely vague because of the community disagreement. It says "The Sprint Retrospective is an opportunity for the Scrum Team to inspect itself and create a plan for improvements to be enacted during the next Sprint," which isn't a statement about who should be there but about what it is for.

This kind of vague statements allow adopting Scrum without agreement on the details, but agreement on the purpose. In my experience, having the PO in a retrospective, in a hierarchical environment, is often a bad idea. Though, I've seen situations where the PO would absolutely need to be there.

In the Scrum Primer, just like Scrum Guide, we're not explicit in it, but are implicitly leaning more towards not having the PO there.

Close this isse?

**Comment by trudelle** [comment]
Scrum itself is anathema in a sufficiently hierarchical environment, a different tool is needed. Obviously, clarity was a red herring, as you seem to be intentionally blurring the intent of the authors of Scrum. I wish you'd be more clear that you're not an advocate of Scrum as it is defined in the Scrum Guide. I heard a strong message in the minimal description of LeSS you presented a few weeks ago in Sunnyvale, CA that it was Scrum at the team level. An asterisk would have been appropriate. LeSS would have more integrity without this claim.

**Comment by basvodde** [comment]
There are differences between LeSS and Scrum as defined in the Scrum guide. What you are pointing out though is not one of them. You are pointing to parts of Scrum of which there is little agreement in the community and which IMHO are purposely left context dependent, for good reasons.

Calling LeSS inconsistent with Scrum at this point is interesting, as I pointed out that the same is true for Nexus, which has been created by the same person as Scrum itself. For that reason alone, I would claim it is not inconsistent with Scrum.

If you do want to learn more about LeSS and the inconsistencies with Scrum, you'll need to look at the definitions of Team/Scrum Team and at self-organization vs self-management. If you claim that LeSS isn't Scrum at these point, I might agree with you. If you argue about a tiny detail of retrospectives, then you are missing the larger picture and purpose.
